I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 1054, in execute_default
    default scene = bg_brain
  File "game/script.rpy", line 1054, in <module>
    default scene = bg_brain
NameError: name 'bg_brain' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 193, in script
    python:
  File "/Users/yanfengwu/renpy-8.3.3/renpy/ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/yanfengwu/renpy-8.3.3/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 194, in <module>
    renpy.execute_default_statement(True)
  File "/Users/yanfengwu/renpy-8.3.3/renpy/exports/statementexports.py", line 372, in execute_default_statement
    i.execute_default(start)
  File "game/script.rpy", line 1054, in execute_default
    default scene = bg_brain
  File "/Users/yanfengwu/renpy-8.3.3/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1054, in <module>
    default scene = bg_brain
NameError: name 'bg_brain' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.3.3.24111502
Decipher 1.0
Mon Jun  2 19:46:39 2025
